feat/no-useless-async
Byndyusoft/bpmnlint-plugin-custom-linter-rules pull request #1
Opened 2024-03-01 17:12 UTC by step1989

2024-03-18 06:52 UTC, lalumiere17 submitted a review, later dismissed

2024-03-21 08:43 UTC, KillWolfVlad requested changes

2024-03-21 08:43 UTC, KillWolfVlad commented on package.json
> +    "build": "echo '(・_・)ノ'",
Можно убрать, CI/CD поймет что скрипта нет и не будет его вызывать

2024-03-21 08:43 UTC, KillWolfVlad commented on package.json
> +    "bpmnlint-utils": "1.1.1"
В библиотеках мы обычно не пиним зависимости, а используем крышечку. Если ли тут необходимость пинить зависимость?

2024-03-21 08:43 UTC, KillWolfVlad commented on package.json
> +    "postinstall": "husky || true",
`|| true` нужен только в сервисах, в библиотеках это не нужно, т.к. postinstall отключается при публикации пакета через pinst

2024-03-21 08:43 UTC, KillWolfVlad commented on README.md
> +# @byndyusoft/bpmnlint-plugin-custom-linter-rules
Тут мы указываем название репозитория

![image](https://github.com/Byndyusoft/bpmnlint-plugin-custom-linter-rules/assets/18448635/57e0146e-5af3-4466-87d4-049a5c24ecc1)

2024-03-21 08:43 UTC, KillWolfVlad commented on README.md
>  [![test](https://github.com/Byndyusoft/node-base-template/actions/workflows/test.yaml/badge.svg?branch=master)](https://github.com/Byndyusoft/node-base-template/actions/workflows/test.yaml)
Нужно обновить ссылки в бейджиках

2024-03-21 08:43 UTC, KillWolfVlad commented on docs/rules/no-useless-async.md
> +Example of **incorrect** usage for this rule:
Предлагаю для лучшей читаемости превратить в заголовок

2024-03-21 08:43 UTC, KillWolfVlad commented on docs/rules/no-useless-async.md
> +Example of **correct** usage for this rule:
Предлагаю для лучшей читаемости превратить в заголовок

2024-03-21 08:43 UTC, KillWolfVlad commented on package.json
> +  "version": "0.0.0",
Вернуть версию как было.

2024-03-21 08:43 UTC, KillWolfVlad commented on README.md
> -- [@KillWolfVlad](https://github.com/KillWolfVlad)
Можешь вписать себя в качестве мейнтейнера

2024-03-21 08:43 UTC, KillWolfVlad commented on README.md
> +yarn add @byndyusoft/bpmnlint-plugin-custom-linter-rules
это dev зависимость, поэтому нужно добавить флаг `-D`

2024-03-21 08:43 UTC, KillWolfVlad commented on README.md
> +  }
Это же не целевое использование? Лучше вынести это в отдельную секцию как пример кастомизации.

2024-03-21 08:43 UTC, KillWolfVlad commented on docs/rules/Readme.md
Предлагаю добавить список всех правил в главное README с отметками о том - является ли правило рекомендуемым.

См. пример https://github.com/sindresorhus/eslint-plugin-unicorn

![image](https://github.com/Byndyusoft/bpmnlint-plugin-custom-linter-rules/assets/18448635/c95da6f7-79b2-48d2-85d9-c4c6ca66c28f)

2024-03-24 15:48 UTC, step1989 commented on README.md
> +# @byndyusoft/bpmnlint-plugin-custom-linter-rules
исправлено

2024-03-24 15:48 UTC, step1989 commented on README.md
>  [![test](https://github.com/Byndyusoft/node-base-template/actions/workflows/test.yaml/badge.svg?branch=master)](https://github.com/Byndyusoft/node-base-template/actions/workflows/test.yaml)
исправлено

2024-03-24 15:50 UTC, step1989 commented on README.md
> +  }
убрал

2024-03-24 15:53 UTC, step1989 commented on docs/rules/Readme.md
возможно это полезно при большом количестве правил. Пока считаю, что списка для старта достаточно

2024-03-24 15:54 UTC, step1989 commented on package.json
> +    "build": "echo '(・_・)ノ'",
исправлено

2024-03-24 15:55 UTC, step1989 commented on package.json
> +    "bpmnlint-utils": "1.1.1"
почему в библиотеках не пиним зависимости?

2024-03-24 15:55 UTC, step1989 commented on package.json
> +    "postinstall": "husky || true",
поправил

2024-03-24 16:00 UTC, step1989 commented on README.md
> +yarn add @byndyusoft/bpmnlint-plugin-custom-linter-rules
поправил

2024-03-28 03:44 UTC, KillWolfVlad commented on package.json
> +    "bpmnlint-utils": "1.1.1"
Чтобы при установке библиотеки она автоматически подтянула все патчи безопасности и улучшения.

2024-03-28 03:53 UTC, KillWolfVlad commented on README.md
> +yarn add @byndyusoft/bpmnlint-plugin-custom-linter-rules
Мы не пишем инструкции инструкции для npm, но можно оставить.

2024-03-28 03:56 UTC, KillWolfVlad approved these changes

2024-03-28 04:00 UTC, merged